name: Build Windows library (kotlin)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build kotlin bindings for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Rust toolchain (stable)
      # For more Rust extensions, please visit: https://github.com/marketplace?query=rust&type=actions
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Cache Rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run:  cargo build --release
    - name: Generate UniFFI bindings
      run:  |
        cargo run --bin uniffi-bindgen generate --library target/release/didresolver.dll --language kotlin --out-dir bindings/kotlin
        cp target/release/didresolver.dll bindings/kotlin/
    - name: Save kotlin artifact
      uses: actions/upload-artifact@v4
      with:
        name: kotlin-bindings-windows
        path: bindings/kotlin
