name: Build Windows library (kotlin)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build kotlin bindings for Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main
    - name: Update Rust
      run:  rustup update
    - name: Cache Rust modules
      id: cache-rust
      uses: actions/cache@v3
      env:
        cache-name: cache-rust-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build
      run:  cargo build --release
    - name: Generate UniFFI bindings
      run:  cargo run --bin uniffi-bindgen generate --library target/release/didresolver.dll --language kotlin
    - name: Save kotlin artifact
      uses: actions/upload-artifact@v4
      with:
        name: kotlin-bindings-windows
        path: target/release/didresolver.dll
